### ISSUE TITLE
ASR parameters

### ISSUE THREAD

**Issue by vpKumaravel** [goodshawn12/REST#10]
Hello,

It is not clear neither in the manuscript nor in the source code - what settings have been used for ASR, especially, what was the ASR cut-off parameter?

Thanks and best regards,

Velu

**Comment by L30045** [comment]
Hello vpKumaravel,

The ASR cut-off parameter control how different the artifact-contained data can be comparing to the no-artifact section. The larger the number is, the more diffence are allowed so that more high-amplitude activities are preserved after ASR. If you want to dig into the source code, the parameters used by ASR pipeline will be listed in _clean_rawdata.m_._ For ASR cut-off parameter specificly, you can find it in _asr_calibrate.m__,

Sincerely,
Chi-Yuan

**Comment by vpKumaravel** [comment]
Thanks Chi-Yuan for the response. So, you used default parameters for the ASR in EEGLAB plugin function. It is clear, now! :)
