### ISSUE TITLE
question about using my data stream

### ISSUE THREAD

**Issue by John-Yao** [goodshawn12/REST#3]
I had create the my data stream by LSL. But it didnot work  when  the num of channels  is not equal to 14.
Here are Matlab error infomation:
onl_append error: The given Name argument must be a string that refers to a variable in the MATLAB workspace, but was: 'BioSemi'
Here are my LSL streaminfo:(completed by python)
info = StreamInfo('BioSemi', 'EEG', 18, 100, 'float32', 'myuid34234')
Is there more infomation about how to using my data stream, such as how to set params.
Thank you!

**Comment by Wagnerdcasag** [comment]
Hello goodshawn12, I'm trying to use REST with my Quick30 headset, but I have been some problems to make the head model. Do you have the head model of Quick30 headset? 
The same problem that John-Yao explained is been  occurring with me:
onl_append error: The given Name argument must be a string that refers to a variable in the MATLAB workspace.
Thank you!

**Comment by goodshawn12** [comment]
The REST should work with Quick30 even without the headmodel (which is only used for source localization). If you saw the error John-Yao had, it's because the number of channels of your Quick30 LSL stream did not math with the default channel locations we have for Quick30.  I am guessing you enabled the ACC channels (accelerometer) so your Quick30 LSL had 3 extra channels. If that's the case, try disable the ACC channels and see if that resolves the issue. Otherwise please provide the whole error messages that occurred so that we can look into it. Thanks!

**Comment by Wagnerdcasag** [comment]
Hi goodshawn12,
I disabled the ACC channels (accelerometer) as you said and it solved the
issue, thanks a lot about that.
The reason I ordered the quick30 head model is because I am interested in
the source location, and I can't make the model. Do you have the head model
of Quick30 headset?

regards,
Wagner Dias Casagrande

Em sex, 11 de out de 2019 às 02:59, goodshawn12 <notifications@github.com>
escreveu:

**Comment by goodshawn12** [comment]
Hi Wagner,
Glad to learn that it works. We don't have a head model for Quick30 right now. But you can use the headModel toolbox (https://github.com/aojeda/headModel) that Alejandro Ojeda developed to create one yourself by specifying the channel location and template. 
Best,
Shawn

**Comment by Wagnerdcasag** [comment]
Hi goodshawn12,
thanks a lot for your help. I will try to make the headmodel with this
toolbox that you sent me. I contact you to talk about the news.

regards,
Wagner Dias Casagrande

Em qui, 17 de out de 2019 às 03:10, goodshawn12 <notifications@github.com>
escreveu:
